app = "tu-app-name"
primary_region = "mia"

[build]
  # Fly detectará automáticamente el Dockerfile

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1